name: Build and Run Quantum Flappy Bird AI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t quantum-flappy-bird .

      - name: Run Docker container
        run: docker run --gpus all quantum-flappy-bird
